name: fast8_payuung
description: "Fast8 Payuung."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.8
  custom_sliding_segmented_control: ^1.8.3
  dartz: ^0.10.1
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_form_builder: ^9.4.1
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^11.0.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/json/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"
  adaptive_icon_foreground: "assets/images/launcher_icon_adaptive.png"
  adaptive_icon_background: "#FBC73D"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FBC73D"
  image: "assets/images/splash_icon.png"
  web: false
